### ISSUE TITLE
Issue with simple text in root

### ISSUE THREAD

**Issue by luwes** [developit/htm#104]
I'm not sure if simple text in the root is supported.
https://codesandbox.io/s/static-0bhft

but I stumbled on a build error once I tried to use the `babel-plugin-htm` for a simple string in the root.

```js
html`Here's a list of items: Count: ${22}`
```

<img width="608" alt="Screen Shot 2019-07-22 at 9 33 18 PM" src="https://user-images.githubusercontent.com/360826/61676001-57eb8400-acc8-11e9-8c1c-1d16e87aa75c.png">

This is a quick fix, just checks if the `node` passed in `transform` is really a `node` and else puts it through the childMapper.

https://github.com/luwes/sinuous/commit/485c944438b1149a5e4c00260102c6bfdff2ab23

**Comment by jviide** [comment]
Good catch! #105 should fix this.

**Comment by jviide** [comment]
...and the fix has now been released as a part of HTM 2.2.
