### ISSUE TITLE
Prop values with slash without quotes

### ISSUE THREAD

**Issue by dy** [developit/htm#106]
```
<a href=/foo/bar>baz</a>
<${Route} path=/home />
```

Prop values containing slash aren't allowed without quotes.
Is there syntactic difficulty recognizing them?

```js
`<a href=//>`

// is empty value allowed?
`<a href= />`
```

**Comment by jviide** [comment]
Thanks for reporting this, @dy! The fix has now been released as a part of HTM 2.2.
