### ISSUE TITLE
Cannot create component from dynamic string

### ISSUE THREAD

**Issue by GresiRoost** [developit/htm#119]
Whatever I do I cannot seem to create a Preact component from a dynamic string.

`<${ComponentClass} ...${options} />`
This doesn't work when using a string ("MyAwesomeComponent" for example).

As far as I could read, React supports creating components if the value is an actual class.
Basically:
`var Type = SiteSetup.getComponentFromName("MyAwesomeComponent");
...
<Type />`

Attempting to do something similar in Preact using HTM would look something like this:
`let ComponentClass = SiteSetup.getComponentFromName("MyAwesomeComponent");`
`<${ComponentClass} ...${options} />`

Unfortunately HTM doesn't understand that the ComponentClass variable is an indirection to the class I want to create - as if I had written `<${MyAwesomeComponent} ...${options} />`

I would really like to avoid having to make a big switch statement for each component in the app ala:

```
function WhichComponent(name, props)
{
    switch(name)
    {
         case 'MyAwesomeComponent':
             return html'<${MyAwesomeComponent} ...${props} />';
         case ..........
    }
}
```

**Comment by developit** [comment]
React does not support creating components that are simple Strings. How would it know what component implementation to render?

**Comment by GresiRoost** [comment]
I get that you can't easily look up a function/class by name except for some terrible hacks (eval/window[name] lookups).

But what about the indirection where the variable does point to the component class I want to create?

**Comment by dy** [comment]
Why not putting all components into some dict and just use that?
```js
let Registry = {}

Registry.MyComponent = function (props) {...}

...

function DynamicComponent(name, props) {
return html`<${Registry[name]} ...${props}/>`
}
```

**Comment by jviide** [comment]
It's somewhat hard to say what went wrong. Seeing a full code example and how it fails (e.g. by throwing exception an exception) would help.

By default HTM should support Preact component classes - if you use the `htm/preact` package - as demonstrated by this CodeSandbox example: https://codesandbox.io/s/preact-htm-lr831nzmmm

**Comment by developit** [comment]
Just to clarify:

```js
// this:
html`<${MyComponent />`
// is:
html(MyComponent)
// which is a reference to a component that we can construct.

// conversely, this:
html`<MyComponent />`
// is:
html("MyComponent")
// which is a String, and it's not possible to look up a reference from a String.
```

Imagine this situation:

```
import html from 'somehwere-else';
function Foo({ ComponentToRender }) {
  return html`<ComponentToRender />`
}
```

The reference is scoped inside of each call to `Foo` - it's impossible to obtain that reference from an opaque string.

---

If you genuinely do want to use String component names, that's actually fairly easy to set up in Preact:

```js
// preact-registry.js
import { options } from 'preact';

// inject our mapping hook into Preact:
let old = options.vnode;
options.vnode = vnode => {
  if (vnode.type in REGISTRY) vnode.type = REGISTRY[vnode.type];
  if (old) old(vnode);
};

const REGISTRY = {}; // our string name to component reference mapping

export function register(name, component) {
  REGISTRY[name] = component;
}
```

```js
// example.js
import { register } from './preact-registry';
import { html, render } from 'htm/preact';

const MyComponent = props => html`
  <h1>Hello ${props.name}!</h1>
`;
register('MyComponent', MyComponent);

render(html`<MyComponent name="GresiRoost" />`, document.body);
```

**Comment by osdevisnot** [comment]
This is how web components work I believe

> While this works and achieves what you've described here, it's considered bad design because it relies on a shared global namespace of components, and registering components into that namespace is a side-effect. Imagine what happens when you import two components that happened to use the same name - you only get the last one. Or, imagine trying to figure out if a given component was still being used in your project - you can't look up uses of the component's in your source code because it could be named anything where it gets used.

**Comment by developit** [comment]
@osdevisnot correct, and it's one of their pain points. There have been multiple efforts to correct this through the use of [scoped registries](https://github.com/w3c/webcomponents/issues/716).
