### ISSUE TITLE
Support for fragments

### ISSUE THREAD

**Issue by pravdomil** [developit/htm#127]
How to do `<>Hello</>` in htm?

**Comment by developit** [comment]
@pravdomil if it's the root of your JSX, just leave the fragment syntax out and it'll happen for you. Within the template, use the literal syntax:

```js
// fragments are implied at the root, just return multiple elements:
function AtTheRoot(props) {
  return html`
    <h1>Hello</h2>
    <h2>World</h2>
  `;
}

// otherwise use the explicit syntax:
function WithinTheTemplate(props) {
  return html`
    <${Fragment}>
      <a />
      <b />
      <c />
    <//>
  `;
}
```

**Comment by broofa** [comment]
Consider reopening?  I'm using the htm+preact standalone build from unpkg, which does not appear to export a `Fragment` property, so the suggested fix doesn't seem to work.  Not sure if I'm doing something wrong or ...?

Furthermore, even if it worked as noted, having to use the explicit `<${Frament}>...</${Fragment}>` notation isn't particularly palatable. (As noted in #176 the ad-hoc component end tag notation is a bit unexpected and I find myself wanting to avoid it, despite its convenience.)  It'd be really nice if the actual JSX `<>...</>` notation for fragments worked as expected.

**Comment by Dmitri-Sintsov** [comment]
As I understand, fragments wrapping are not requited with htm, thus these are not included into standalone build?

Is there a regularly updated official standalone preact+htm build, by the way?

I prefer to develop without bloated node.js tools, especially because modern browsers support most of features without transpiling.
