### ISSUE TITLE
htm typing file doesnt seem to be included

### ISSUE THREAD

**Issue by Darkle** [developit/htm#135]
Hi, the htm type file that was added in [this PR](https://github.com/developit/htm/pull/123) doesn't seem to be in the folders after an install. Only the react/preact type files seem to have been included.

I'm using version 2.2.1 of htm.

Here is a screenshot of the folder structure in the node_modules directory after installation: https://i.imgur.com/qjouzZs.png

Cheers.

**Comment by developit** [comment]
Ah darn - it's at `src/types.d.ts`, but the `package.json` is pointing to `dist/types.d.ts`.

**Comment by developit** [comment]
Hiya - this is fixed in HTM 3, the types are now in `dist`.
