### ISSUE TITLE
Remove the dependency on `document`

### ISSUE THREAD

**Issue by tunnckoCore** [developit/htm#14]
First, great job again! :tada: 

Do we really need to use `template` tag for the magic? :D

**Comment by TejasQ** [comment]
I'd +1 this because it'd be kind of cool to generate HTML (using vhtml in conjuction with this) on the server side for server-rendered UIs. Because of the dependency on `document`, this doesn't quite work in a node environment without extra dependencies, unless there's something I'm missing.

**Comment by TejasQ** [comment]
Yes. Unfortunately though, I'm profiling performance (for science) and I'm afraid of adding overhead to my benchmarks. Oh well, I'm sure OUR BOI Jason will come up with something cool soon.

**Comment by TejasQ** [comment]
Dang, that was fast. Thank you! 🙏

**Comment by azl397985856** [comment]
> I have a custom parser I've converted htm over to, I'll publish it soon. Should run in any JS environment.

too much to expect

**Comment by tunnckoCore** [comment]
Cool. We can close. ;]

**Comment by TejasQ** [comment]
@developit  I love you ❤️
