### ISSUE TITLE
Document fragment as multiple elements

### ISSUE THREAD

**Issue by dy** [developit/htm#15]
There was a discussion in JSX spec to enable fragments as first class citizen via just multiple elements, which is really natural syntax for fragments, https://github.com/facebook/jsx/issues/58.
For me that would be a killing feature for htm.
```js
return html`
            <${Header} name="ToDo's (${page})" />
            <ul>
              ${todos.map(todo => html`
                <li>${todo}</li>
              `)}
            </ul>
            <button onClick=${this.addTodo.bind(this)}>Add Todo</button>
            <${Footer}>footer content here<//>
        `;
```
Any thoughts on enabling that?

**Comment by manucorporat** [comment]
https://github.com/developit/htm/pull/30

**Comment by jviide** [comment]
Support for this was added in [v2.1.0](https://github.com/developit/htm/releases/tag/2.1.0) 🙌And it works great with Preact X (current preact@next, see this [CodeSandbox example](https://codesandbox.io/s/lr831nzmmm)).
