### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by talentlessguy** [developit/htm#155]
Would be cool to have a VS Code plugin that will highlight `html` strings like JSX, so all JSX autocomplete will work. Also formatters like Prettier will understand the markup and fix its indentation.

**Comment by talentlessguy** [comment]
I'm a dumbass who didn't read the readme

**Comment by alimertcakar** [comment]
lit-html does not highlight preact components written as <${Button}/> 
Any solution for that?

**Comment by victmo** [comment]
I second @alimertcakar, the lit-html extension doesn't highlight components. Is there a workaround or configuration that could fix this?

![image](https://user-images.githubusercontent.com/358122/111103952-f1168080-8525-11eb-98e0-8129d207c15e.png)
