### ISSUE TITLE
Fast h function

### ISSUE THREAD

**Issue by PeteSolid** [developit/htm#157]
Hello there!

Do you have a recommendation for a fast h function? _(framework-agnostic)_
I found a [tweet from developit](https://twitter.com/_developit/status/1232748388929736704) for a short one. 

```
function h(el, props, ...kids) {
  el = document.createElement(el)
  for (let i in props) i in el
    ? el[i] = props[i]
    : el.setAttribute(i,props[i])
  el.append(...kids)
  return el
}
```

But after running some tests, I think this could be more performant. Sadly I do not have the knowledge where to look at.
Thank you for the help!
Pete

**Comment by Grafikart** [comment]
This function doesn't handle kids that contains array close to textNode (or other Node). It won't handle event listener too. Here is my current approach. I don't know if it's fast but it covers all the edge case I encountered at the moment (maybe it helps)

```js
/**
 * @param {string} tagName
 * @param {object} attributes
 * @param {...HTMLElement|string} children
 * @return HTMLElement
 */
export function createElement (tagName, attributes = {}, ...children) {
  // On construit l'élément
  const e = document.createElement(tagName)

  // On lui associe les bons attributs
  for (const k of Object.keys(attributes || {})) {
    if (k.startsWith('on')) {
      e.addEventListener(k.substr(2).toLowerCase(), attributes[k])
    } else {
      e.setAttribute(k, attributes[k])
    }
  }

  // On aplatit les enfants
  let flattenChildren = []
  for (const child of children) {
    if (Array.isArray(child)) {
      flattenChildren = [...flattenChildren, ...child]
    } else {
      flattenChildren.push(child)
    }
  }

  // On ajoute les enfants à l'élément
  for (const child of flattenChildren) {
    if (typeof child === 'string' || typeof child === 'number') {
      e.appendChild(document.createTextNode(child))
    } else if (child instanceof HTMLElement) {
      e.appendChild(child)
    } else {
      console.error("Impossible d'ajouter l'élément", child, children)
    }
  }
  return e
}
```

**Comment by dy** [comment]
FYI. There's multiple existing hyperscript implementations:
* [hyperscript](https://ghub.io/hyperscript)
* [hyperscript-sctrict](https://github.com/dmitriz/hyperscript-strict)
* [hyps](https://github.com/ahdinosaur/hyps)
* [html-tag](https://www.npmjs.com/package/html-tag)

**Comment by Grafikart** [comment]
@PeteSolid  [jsx-dom](https://github.com/proteriax/jsx-dom) seems to be a more robust solution than my snippet

**Comment by PeteSolid** [comment]
@Grafikart 
Thank you all!
I tried it with inline functions and it worked.

```
const click = () => console.log(1);
const elem = html`
  <div onclick=${click} id="app">Click here</div>
`;
```
But I see your point that maybe inline expresions may not work.
Could you give me a simple example of the case "kids that contains array close to textNode (or other Node)", please?

**Comment by Grafikart** [comment]
@PeteSolid I got an issue with this : 

```js
const items = [1, 2, 3, 4, 5]
html`
<ul>
  <li>
    <span>Hello</span>
    ${items.map(i => html`<span>${i}</span>`)}
  </li>
</ul>`
```

I expected the <li> h function to receive a children with 6 items but I receive 2 children, one <span> and one array of <span>{item}</span>.

I did a small code sandbox to show the problem : https://codesandbox.io/s/busy-sun-f4db5

**Comment by developit** [comment]
The Array behavior is expected - flattening Arrays would remove valuable position data, and it's possible to do in userland, whereas trying to obtain position data from pre-flattened children is impossible.

**Comment by developit** [comment]
I'm going to close this one out now since it seems like we've got some decent solutions.

For the nested Arrays thing, you can use `.flat()`:

```js
  el.append(...kids.flat(Infinity))
```
