### ISSUE TITLE
Missing childNodes when creating Elements in a loop?

### ISSUE THREAD

**Issue by Krutsch** [developit/htm#158]
Hi,

when I push new created elements in an array and access them afterwards, the _childNodes_ Attribute looks really weird. Here is an example

```
import htm from "https://unpkg.com/htm?module";
function h(el, props, ...kids) {
  el = document.createElement(el)
  for (let i in props) i in el
    ? el[i] = props[i]
    : el.setAttribute(i,props[i])
  el.append(...kids)
  return el
}
var html = htm.bind(h);


const elems = [];
for (let i = 0; i < 2; i++) {
  const elem = html`
    <div id="app">
      <p>Value:</p>
      <p>This ${i}</p>
    </div>
  `;
// elems.childNodes.forEach(child => console.log(child.textContent));  // would log the correct childNodes
  elems.push(elem);
}

elems[0].childNodes.forEach(child => console.log(child.textContent)); 
// logs "This 0"
```
So the p element with the textNode 'Value' is missing after pushing it to the array and accessing it for every elems Element beside the last one.
I thought it might be because of the **h function** but I have the same problem with other functions.

**Comment by developit** [comment]
I think this might be a result of the caching introduced in version 3. `<p>Value:</p>` is static and when you call `el.append(...kids)` in the second iteration of the loop, you're actually moving the previous call's cached nodes into the new parent.

I believe the solution is to add this to the first line of your `h()` function:

```
function h(el, props, ...kids) {
  this[0] = 0;
}
```

@jviide can correct me here if I'm wrong.

**Comment by jviide** [comment]
Yes, I believe @developit is correct. The caching behavior can be disabled with `this[0] = 3` (_not_ `this[0] = 0` like I instructed @developit in Slack, sorry about that!). 

That said, the first alternative solution is an interesting idea, as it (probably) solves this and takes advantage of the cache.

**Comment by developit** [comment]
Yeah the `cloneNode(true)` version is my personal pick. For large static subtrees that'll be a ton faster than recreating them on-the-fly.

**Comment by Krutsch** [comment]
Cool, that helped, thank you both 🙌
