### ISSUE TITLE
Text "div" is included in the DOM

### ISSUE THREAD

**Issue by maxkerp** [developit/htm#162]
Hi there,

I'm using preact and htm to create a realtime web based representation of the dice game schocken.

Somehow when rendering `img` tags it renders or includes text in the DOM which says "div" and I can't seem to figure out what the reason for this is.. :grimacing: 

Does anybody here have an idea what I'm doing wrong?

BTW thanks for this awesome tech! It rocks :metal: 

![Screenshot from 2020-04-11 15 45 23](https://user-images.githubusercontent.com/4179529/79045457-83721e00-7c0b-11ea-8c9c-653b091f0438.png)

**Comment by dy** [comment]
Can you provide the code example?

**Comment by maxkerp** [comment]
Hey thank you so much for the quick response :+1: 

This was exactly my problem. I forgot to close the `img` tags.. :see_no_evil: 
After closing them, everything works as expected.

Thanks!
