### ISSUE TITLE
DOM re rendering!

### ISSUE THREAD

**Issue by mohammedzamakhan** [developit/htm#17]
https://codesandbox.io/s/k5l26zrxy3

**Comment by mjarkk** [comment]
I don't this this is re-rendering the full dom  
Open the chrome inspector and select that clock  
You will see that only the clock updates

**Comment by mohammedzamakhan** [comment]
Thats why I closed it, codesandbox was re rendering the whole dom when I changed the code, so codesandbox was a bit misleading
