### ISSUE TITLE
Missing ./preact export map

### ISSUE THREAD

**Issue by balakine** [developit/htm#181]
I believe Skypack CDN needs it to turn deep import specifiers into ESM-compatible ones. I'd like to do this:
```javascript
import { html } from 'https://cdn.skypack.dev/htm@3/preact';
```
Funny enough they use your other project in their example https://docs.skypack.dev/lookup-urls/lookup-urls#lookup-a-package-export
```javascript
import { useState } from 'https://cdn.skypack.dev/preact@10/hooks';
```
Maybe it needs preact in peerDependencies in `src/integrations/preact/package.json` too.

**Comment by developit** [comment]
This should be fixed as of [version 3.1.0](https://github.com/developit/htm/releases/tag/3.1.0).
