### ISSUE TITLE
[Feature request] ESLint plugin

### ISSUE THREAD

**Issue by Fordi** [developit/htm#183]
For the most part this just works, but functions within tagged markup get weird indent assertions, e.g.,
```
        ${collection.map((item) => {
          const { prop1, prop2 } = workWith(item);  // eslint: expected indentation of 4 but found 10 (indent)
          return html`  // eslint: expected indentation of 4 but found 10 (indent)
            <${Widget} prop1=${prop1} prop2=${prop2} />
          `;
        })} // eslint: expected indentation of 2 but found 8 (indent)
```

So I'd request an eslint plugin where you could specify the name of the template function, and make the linter comprehend it, or directions to the resources I'd need to implement one.

**Comment by Fordi** [comment]
I found `eslint-plugin-lit`, which fixes the indent problem, albeit by disabling `lit/binding-positions` (👍 ) and `lit/no-invalid-html` (😢  ).  If anyone has any further tips, I'd love to hear 'em.

**Comment by developit** [comment]
Starting from the Lit plugin is a great idea - I'd begun hacking on something, but quickly realized it was going to take a lot more work than I had time to prototype.

**Comment by ruffin--** [comment]
It looks like [spread attributes](https://reactjs.org/docs/jsx-in-depth.html#spread-attributes) are also a show-stopping issue with eslint.

Telling eslint...

        "ecmaFeatures": {
            "jsx": true
        }

... corrects this for JSX, but obviously doesn't extend to string literals in htm.

Painful b/c it's not an eslint rule you can disable and continue linting; it's an eslint _parsing_ issue, so it kills eslint for the file completely.

<img width="615" alt="showing a spread attribute giving a parsing error in eslint" src="https://user-images.githubusercontent.com/5659878/161597320-6d0b0856-2d71-4bf8-95a3-d605c782dff3.png">

Is there a clever rewrite around this that I'm missing?

**Comment by GGabrielDev** [comment]
This is kinda old, I know, but there's no progress with this? Would be nice to integrate EsLint to my project knowing that it will work out nicely with HTM.

Sadly, I'm still not savvy enough to write my own EsLint plugin :(

**Comment by mtsknn** [comment]
@Fordi Did you manage to find an ESLint plugin for HTM, given that you closed this issue?

**Comment by Fordi** [comment]
No.  But the lit plugin with some configuration to allow for htm's wider syntax support has been "good enough" for the last few years.  Mostly, I closed it (and a lot of other outstanding issues that don't look like they're getting fixed any time soon) because I use my GitHub issues at my new job to track active work, and this issue is kinda just polluting that.

**Comment by mtsknn** [comment]
> But the lit plugin with some configuration to allow for htm's wider syntax support has been "good enough" for the last few years.

That's good to know, thanks!
