### ISSUE TITLE
onClick isn't registering in functional component

### ISSUE THREAD

**Issue by willmartindev** [developit/htm#193]
I am working on a Preact app using server side rendering and htm.

In the component below, I can't get the onClick handler to fire when clicked. 

```
const HistoryListItem = ({ historyItem, key }) => {
    const handleClick = () => {
        console.log("test")
    }
    
    return html`
        <li onClick=${handleClick}>
            ${historyItem.toString()}
        </li>
    `;
}
```

I have tried `onClick=${() => handleClick()}` and `onclick` as well. I am coming from React, so I may be missing something super obvious. Any idea what is going on?

**Comment by dy** [comment]
It depends on what is `html` function here.

**Comment by willmartindev** [comment]
It turns out I just didn't understand the implications of server side rendering! My error.
