### ISSUE TITLE
Question: blueprintjs + htm

### ISSUE THREAD

**Issue by gurpal2000** [developit/htm#197]
Has anyone successfully used blueprintjs (https://blueprintjs.com) with htm and es-react?

Loading CSS is fine, but how does one import @blueprintjs/core in the htm "no-build tools" environment and use say a simple Button widget? Does it require blueprint to modularise somewhat?

thanks

**Comment by developit** [comment]
You'd have to use the UMD bundles for Blueprint, otherwise it will attempt to import `react`, which will fail.
