### ISSUE TITLE
(Question) How to ensure a whitespace between two elements?

### ISSUE THREAD

**Issue by jakub-g** [developit/htm#202]
I've been playing with `htm`, and I have `prettier` in my repo which formats code automatically.

I'm struggling to output a space between two elements; sometimes I end up with prettier formatting code like this:

```
      html`<span>long text long text long text</span>
      <span>foor bar</span>`
```

I want a single space between the two spans, but regular spaces get collapsed; and `&nbsp;` is escaped and output literally as ` `&nbsp;`.

Is there a clean solution to this?

**Comment by timonson** [comment]
I would love to hear an answer to this question, too.

**Comment by antelle** [comment]
`${' '}` seems to work: [jsfiddle](https://jsfiddle.net/kdLyso45/1/)

```js
html`<div>
  <span>sp</span>
  ${' '}
  <span>ace</span>
</div>`
```

**Comment by developit** [comment]
Yep, the expression with a space character is the way to go here, since it's the same behavior as JSX.
