### ISSUE TITLE
Question: Why not always return an Array?

### ISSUE THREAD

**Issue by timonson** [developit/htm#204]
Hi guys, I really like your `htm` function and the performance of it! But the *undetermined* return type causes a lot of complications especially with regards to the usage of nested function calls.

There is probably a good reason why you chose this return type and I would love to know it. Otherwise I would consider it to be bad design and I would suggest changing it.

Would you also be so kind and clarify for me which one of these two alternatives is exported in the CDN version: `export default MINI ? build : regular;` ?

Thanks!

**Comment by developit** [comment]
Always returning an array is expensive for implementors because it creates an implicit fragment that has its own diff overhead. 

Both versions are hosted on unpkg, the default is the full version. Mini is at https://unpkg.com/browse/htm@3.0.4/mini/

**Comment by timonson** [comment]
Thanks!
