### ISSUE TITLE
Inline elements at the beginning of a line do not have preceding whitespace.

### ISSUE THREAD

**Issue by milochristiansen** [developit/htm#206]
If you have a large block of text that is broken up into lines in the source for readability, and you happen to get unlucky enough to have an inline element at the beginning of the line, the element will not be separated from the preceding content with a space in the rendered output.

Take the following fragment:
```js
html`
	Test line 1.
	Test line 2.
	<i>Test</i> line 3.
`
```
The rendered output that would be expected would be something like:

> Test line 1. Test line 2. *Test* line 3.

instead you get:

> Test line 1. Test line 2.*Test* line 3.

(Note the missing space)

This an issue because in page layouts with large paragraphs you are basically playing with fire. You can very easily run into a case where you have a "typo" despite the source being correct. It is possible to work around this issue, but that requires you to A) be aware of it and B) not be silently screwed by automated formatting tools.

**Comment by developit** [comment]
This is actually "working as designed" - it's the same output JSX generates:

```js
// this:
<>
    Test line 1.
    Test line 2.
    <i>Test</i> line 3.
</>;

// compiles to this:
h(Fragment, null, "Test line 1. Test line 2.", h("i", null, "Test"), " line 3.");

// which renders:
"Test line 1. Test line 2.<i>Test</i> line 3."
```

**Comment by milochristiansen** [comment]
Well... That output is problematic. It certainly violates the law of least astonishment. Is it perhaps a JSX bug?

**Comment by developit** [comment]
It was a grey area that the JSX spec/proposal did not describe, so the standard ended up being set by what the original Babel and Acorn implementations chose to do.
