### ISSUE TITLE
Dynamic Loading?

### ISSUE THREAD

**Issue by renhiyama** [developit/htm#223]
Currently its not possible to run htm like this:
```js
htm`${"<p>hello</p>"}`
```
making it hard for me to dynamically load jsx over the internet.

**Comment by GjeloshajAntoine** [comment]
Shouldn't you call it like a function such as `htm("<p>hello</p>")` ?

**Comment by renhiyama** [comment]
@GjeloshajAntoine that's not possible, htm uses template string functions so you can't use `()` but you need to use \` \`.
Anyways I would like to close this issue since I've made dynamic loading, and it will be available as a framework soon at https://github.com/rovelstars/reejs
(Currently it doesn't supports other sites, but I will rewrite it soon to make that happen 😄)
