### ISSUE TITLE
[Question/request] is there a list of known html compat issues?

### ISSUE THREAD

**Issue by bigopon** [developit/htm#225]
I tried to search within the repo but couldnt find any. I wanted to see how well htm can be used to handle html parsing. The goal isnt to have all the forgiveness of html, just need to be good for all the standard pattern/usage.
Also, maybe can we have that stated in the readme?

**Comment by developit** [comment]
@bigopon HTM 2 & 3 aren't particularly well suited to HTML parsing, since we switched to emulating JSX syntax more closely than HTML.

You can use HTM 1 though - it uses the browsers HTML parser and matches HTML behavior 1:1.

**Comment by bigopon** [comment]
Thanks @developit
