### ISSUE TITLE
How to append dynamic value? like ``jsx`${value_from_var}```

### ISSUE THREAD

**Issue by ooling** [developit/htm#230]
Last night I wrote
```
let jsx = htm.bind(h);
let data = '<p>test</p>
let Test =()=> jsx`${data}`
render(Test(), document.querySelector('#content'));
```
But it just render plain text instead `p` element.
How to solve that?
Anyway I'm using ES Module right in the browser without NodeJS nor Bundle system.

**Comment by rschristian** [comment]
This will do the trick:

```js
let jsx = htm.bind(h);
let data = '<p>test</p>';
let Test = () => jsx([data]);
render(jsx`<${Test} />`, document.querySelector('#content'));
```

**Comment by ooling** [comment]
@rschristian sure it worked, but it didn't work when I'm tried using functional component

**Comment by rschristian** [comment]
What do you mean? That is a function component.

**Comment by ooling** [comment]
@rschristian When using _hooks_ I meant

**Comment by rschristian** [comment]
Okay, and how are you attempting to use hooks? It's a bit difficult to help you if I can't see what you're trying to do.

Edit: [Here's an example of a component that uses your HTML string and has hook state](https://esm.rschristian.dev/#Ly8gU2ltcGxlIGFwcCBieSBAcnNjaHJpc3RpYW4gZm9yIGh0dHBzOi8vZ2l0aHViLmNvbS9kZXZlbG9waXQvaHRtL2lzc3Vlcy8yMzAjaXNzdWVjb21tZW50LTEzMjEwMTY1ODIKLy8gLS0tLS0tLS0tLS0tLS0tLQoKaW1wb3J0IHsgaHRtbCwgcmVuZGVyLCB1c2VTdGF0ZSB9IGZyb20gJ2h0dHBzOi8vY2RuLnNreXBhY2suZGV2L2h0bS9wcmVhY3Qvc3RhbmRhbG9uZSc7Cgpjb25zdCBkYXRhID0gJzxoMSBzdHlsZT0iY29sb3I6IHdoaXRlIj5IZWxsbyBXb3JsZCE8L2gxPic7CgpmdW5jdGlvbiBBcHAoKSB7CiAgICBjb25zdCBbc2NvcmUsIHNldFNjb3JlXSA9IHVzZVN0YXRlKDApOwogICAgY29uc3QgQnV0dG9uID0gKCkgPT4gaHRtbGA8YnV0dG9uIG9uQ2xpY2s9JHsoKSA9PiBzZXRTY29yZShzY29yZSArIDEpfT4ke3Njb3JlfTwvYnV0dG9uPmA7CiAgICAKICAgIHJldHVybiBodG1sYAogICAgICAke2h0bWwoW2RhdGFdKX0KICAgICAgPCR7QnV0dG9ufSAvPgogICAgYDsKfQoKcmVuZGVyKGh0bWxgPCR7QXBwfSAvPmAsIGRvY3VtZW50LmJvZHkpOw==). Hopefully this is what you're looking for?

**Comment by ooling** [comment]
can you just share the code here?
it looks mesy :
![Screenshot_20221120-213009770](https://user-images.githubusercontent.com/33863355/202908148-aba57f89-56db-4226-b8e8-467506bb4b52.jpg)

**Comment by rschristian** [comment]
>  it looks mesy :

That looks to be a rendering error in your browser, quite frankly. I'd use something else. It's like elements are duplicated out of place and without styling. Really odd.

> can you just share the code here?

```js
import { html, render, useState } from 'https://cdn.skypack.dev/htm/preact/standalone';

const data = '<h1 style="color: white">Hello World!</h1>';

function App() {
    const [score, setScore] = useState(0);
    const Button = () => html`<button onClick=${() => setScore(score + 1)}>${score}</button>`;
    
    return html`
      ${html([data])}
      <${Button} />
    `;
}

render(html`<${App} />`, document.body);
```

**Comment by ooling** [comment]
It worked, noice!
