### ISSUE TITLE
How to install with preact, yet no packaging step?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [developit/htm#233]
Hello there,

I would like to have something like the standalone module package, yet store it locally. I can't use eg. vite packaging as the files need to be available as JS modules at runtime for a plugin architecture.

Apologies - my brain is kinda shutting down at the thought of how this should be done.

I'm only thinking "copy files manually from unpkg" but that isn't really professional ...

Is the way to install the NPM package and then reach into that through copying?

Do you have any tips, hint, leads? 🤔

**Comment by rschristian** [comment]
> I'm only thinking "copy files manually from unpkg" but that isn't really professional ...

There's nothing wrong with that, tbh.

You can clone the repo, build it, then use something like [`yalc`](https://npm.im/yalc) to publish & install locally. That seems to be what you're after?

**Comment by bjorn-ali-goransson** [comment]
Thanks. I believe I will use Vite with preact as "external" in order not to bundle it, and use some kind of manual copying mechanism from my node_modules.

Thank you dearly for you support!

**Comment by bjorn-ali-goransson** [comment]
Hmm ... OK; this works. Almost.

```javascript
import { defineConfig } from 'vite';
import preact from '@preact/preset-vite';
import fs from 'fs';
import alias from '@rollup/plugin-alias';

export default defineConfig({
  plugins: [preact()],
  build: {
    rollupOptions: {
      external: [
        './preact-htm/standalone.module.js'
      ],
      output: {
        entryFileNames: '[name].bundle.js',
        assetFileNames: '[name].[ext]',
        chunkFileNames: '[name].[ext]'
      },
      plugins: [
        {
          name: 'copy-files',
          generateBundle: () => fs.copyFileSync('node_modules/htm/preact/standalone.module.js', '../wwwroot/preact-htm/standalone.module.js')
        },
        alias({
          entries: [
            { find: '@preact-htm', replacement: './preact-htm/standalone.module.js' }
          ]
        })
      ]
    },
    sourcemap: true,
    outDir: '../wwwroot'
  }
});
```

Now, my problem is that the standalone module (with both HTM and Preact prepackaged) does not include eg. hooks. How to do this? I'm guessing just package it yourself?

eg https://github.com/developit/htm/pull/134

**Comment by bjorn-ali-goransson** [comment]
Oh, wait, the standalone does include them! You just don't need to import 'preact/hooks'. I think we're good here!

**Comment by bjorn-ali-goransson** [comment]
![image](https://user-images.githubusercontent.com/668160/208663263-af5657f9-30ce-4c61-8160-2b6d65af299f.png)
