### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by jzaefferer** [developit/htm#25]
For a library supposed to run directly in the browser, it would be nice to list the browser support. From what I can tell, IE<=11 won't work, due to the template element not being supported: https://caniuse.com/#feat=template

Are there other limitations?

**Comment by developit** [comment]
There is a fallback for browsers that don't support `<template>`, so the only requirement here is basic DOM. Tagged Templates are the limiting factor for browser support, but that goes away if you compile using the Babel plugin.
