### ISSUE TITLE
How to correctly handle these double quotes?

### ISSUE THREAD

**Issue by jake-danton** [developit/htm#258]
I am trying to figure out how to get this valid html working with `htm`:
```
html`
      <html>
        <head>
            <script type="importmap">
                {
                    "imports": {
                        "preact-iso": "https://esm.sh/preact-iso@2.4.0"
                    }
                }
            </script>
...
```

As is, it renders as:
```
<html><head><script type="importmap">{&quot;preact-iso&quot;:&quot;https://esm.sh/preact-iso@2.4.0&quot;}}</script>
...
```

Which is invalid HTML. And single quotes won't work here as it keeps them single quotes in the output and the result is invalid JSON.

Is there a way to correctly handle this? Something like [unsafeHtml](https://lit.dev/docs/templates/directives/#unsafehtml) in `lit` that would let me concatenate the JSON object as a string directly parsed as a VNode?

**Comment by rschristian** [comment]
`dangerouslySetInnerHTML` is what you want:

```js
const MAP = {
    imports: {
        "preact-iso": "https://esm.sh/preact-iso@2.4.0"
    }
};

const doc = html`
    <html>
        <head>
            <script type="importmap" dangerouslySetInnerHTML=${{ __html: JSON.stringify(MAP) }}></script>
        </head>
    </html>
`;
```

**Comment by jake-danton** [comment]
Thank you @rschristian !
