### ISSUE TITLE
Join forces with TJSX

### ISSUE THREAD

**Issue by fabiosantoscode** [developit/htm#26]
I've long ago created a project like this, TJSX, and I feel we can join forces and create something even better.

Want to do it?

**Comment by dogoku** [comment]
Or https://github.com/WebReflection/hyperHTML
Or https://github.com/Polymer/lit-html

**Comment by developit** [comment]
The output format for HTM isn't an implemention detail, it's the library's sole purpose. It's true the authoring format looks similar to many other solutions, but the point here is that HTM brings that solution to the Virtual DOM landscape. 

It's similar in nature to hyperx, but with additional features from JSX like dynamic tag names and spreadable props.

**Comment by rbiggs** [comment]
@dogoku. Both HyperHTML and lit-html are libraries that include tagged templates for markup, somewhat similar to htm, but they also render those directly to the DOM. They also have solutions to create components, data-binding, etc. They are competing with every other front end library out there. HyperHTML and lit-html are competitors in the space for non virtual dom template string solutions. Htm is not in that space. Htm is about enabling a JSX-like syntax in the browser for libraries which would normally require a build step to transpile JSX. Htm converts tagged templates into a virtual node for use by libraries that have virtual DOMs. As such, it works with React, Preact, Inferno, Vue, Hyperapp, etc., anything that has a virtual DOM and can use JSX. Thank you so much for this solution @developit

**Comment by developit** [comment]
Regarding the original topic here - the two seem to take fairly different approaches. What would joining forces mean in this context?
