### ISSUE TITLE
如何使用bun+preact+htm构建我的前端项目工程呢

### ISSUE THREAD

**Issue by AERCR3** [developit/htm#260]
如何使用bun+preact+htm构建我的前端项目工程呢？？
目前看作者是在维护npm下的程序包，未来是否有想法抽出一定的开发时间在bun下载构建包呢？bun似乎已经构建了npm包的解释器了

**Comment by rschristian** [comment]
Is there a problem with installing the package? You should be able to use `bun install htm` without issue, Bun is meant to be able to use standard NPM modules.

**Comment by AERCR3** [comment]
是的，我在中国做一些前端的工作，但是我在努力克服，我的网络不是很稳定，似乎是网络的问题，谢谢您的回复
