### ISSUE TITLE
Beginner friendly babel-plugin-htm

### ISSUE THREAD

**Issue by PeteSolid** [developit/htm#47]
Hi, I'm relatively new to web development and only know a little about babel - and webpack.
So I want to start a new project and have my webpack config which holds my babel config. I don't know if this is best practice ... anyway - I would like to add the plugin but I am struggeling with it.

Is it possible to change the readme for this plugin so that noobs like me can understand where to put:
`[
  ["htm", {
    "pragma": "React.createElement"
  }]
]`

Thank you for htm!

**Comment by developit** [comment]
I think we can do that! Maybe little sections for each that you can click to show.

**Comment by developit** [comment]
Also just a note - you don't need the Babel plugin at all to get started. It's just if you want to compile HTM down to function calls in production, perhaps to support IE11.

**Comment by PeteSolid** [comment]
Yes, thanks for the note 😄 Also less Bytes to send for the user 👀 
So it's opt-in but I like to make the most out of it

**Comment by developit** [comment]
@PeteSolid this is actually one case where performance can be quite counterintuitive :)  I'm going to be publishing some results soon that show it can be beneficial to ship HTM and parse Tagged Templates at runtime since it considerably reduces the parse cost of large applications otherwise built with JSX.

**Comment by PeteSolid** [comment]
That's interesting ! OK, thats closes the relevance of the initial Issue 😃

**Comment by developit** [comment]
Definitely! I'm hoping to publish things soon, and then it would be a good time to revisit htm's readme and adjust some of the positioning around our Babel integration.
