### ISSUE TITLE
how to convert jsx to htm?

### ISSUE THREAD

**Issue by jimmielemontgomery** [developit/htm#55]
How can I convert my existing jsx project to use htm as tagged template literals (possibly using babel)?
Is there a convenient configuration for transforming my project easily?

Thanks very much,

**Comment by developit** [comment]
I have a Babel plugin coming for this.

**Comment by jimmielemontgomery** [comment]
@developit this is a babel plugin specifically for translating JSX to tagged template literals:
https://gist.github.com/jimmielemontgomery/155642bb46784125c1c6695a6da48c9b

It has usage and development notes as well as customizable [tagname](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

**Comment by developit** [comment]
Awesome @jimmielemontgomery! I have one written as well, we should combine. Hoping to PR it soon.

**Comment by developit** [comment]
Fixed! It's called [babel-plugin-transform-jsx-to-htm](https://www.npmjs.com/package/babel-plugin-transform-jsx-to-htm):

```sh
npm i -D babel-plugin-transform-jsx-to-htm
```

in `.babelrc`:
```json
{
  "plugins": [
    ["transform-jsx-to-htm", {
      "import": "htm/react"
    }]
  ]
}
```
