### ISSUE TITLE
Question: How well does this work with TypeScript?

### ISSUE THREAD

**Issue by ryansmith94** [developit/htm#73]
Hey, apologies to take your time on a question I could answer myself with a few minutes of trying it out (and I still might do that if I get a few minutes). It would be nice to just have a quick answer to this question somewhere in this project, maybe in the readme. I guess specifically I'd like to know the following.

1. Does this package have typings?
2. Does TypeScript provide compile time errors for passing incorrect prop values to components when using this package?

**Comment by developit** [comment]
1. there aren't typings for `htm` / `html`, but there are extremely basic types for the react and preact integrations.
2. No. For this and the typings, TypeScript doesn't have a way to inspect the contents of Tagged Templates (or Template Literals). This means we can't really offer any useful inference for what a tagged template contains.

I kicked off a discussion with the TypeScript folks about this (and more generally about extending type checking into tagged templates). You might find the discussion interesting:
https://github.com/Microsoft/TypeScript/issues/29432

**Comment by developit** [comment]
FWIW, you can use TSX and get all the TypeScript benefits, tell TS to leave TSX in-tact via `jsx:'preserve'` when compiling, then pass the result through `babel-plugin-transform-jsx-to-htm` and still be using HTM at runtime.

**Comment by ryansmith94** [comment]
Okay thanks @developit. For now then it looks like this unfortunately isn't really viable for use with typescript and the conversation with the typescript folkes appears to have gone stale (no comments for a month). Cool project though.

**Comment by bebraw** [comment]
@ryansmith94 TypeScript will receive support for tagged templates. See https://github.com/microsoft/TypeScript/pull/40336 .

I believe you should be able to type `htm` on top of that although that may not be a trivial task.

**Comment by jugglinmike** [comment]
TypeScript 4 took a step in the right direction, but it looks like it's still not quite possible:

- [microsoft/typescript - gh-31422 - const TemplateStringsArray for TaggedTemplateExpression](https://github.com/microsoft/TypeScript/issues/31422)
- [microsoft/typescript - gh-33304 - Type safety with TemplateStringsArray and tag functions](https://github.com/microsoft/TypeScript/issues/33304)
