### ISSUE TITLE
css prop

### ISSUE THREAD

**Issue by nikitapilgrim** [developit/htm#88]
The idea is just great, but I ran into a problem.
How to use with emotions?
![Screen Shot 2019-05-12 at 21 40 47](https://user-images.githubusercontent.com/49089372/57586492-54d15c00-74ff-11e9-83b6-9b6522f97f3e.png)
![Screen Shot 2019-05-12 at 21 45 18](https://user-images.githubusercontent.com/49089372/57586495-5864e300-74ff-11e9-9612-b17cc9a68165.png)

**Comment by developit** [comment]
@nikitapilgrim are you using Preact, or React?

**Comment by nikitapilgrim** [comment]
preact X

**Comment by developit** [comment]
Ah - this is likely a Preact X issue, not an HTM issue.

Would it be possible for you to set up a repro for this? I'd really like to look into it, but it'll be pretty specific to your emotion setup (whether you're using the babel plugin, etc).

**Comment by developit** [comment]
This should be fixed as of `preact@10.0.0-beta.2`, released a couple days ago.
