### ISSUE TITLE
Should fragments return one `h` call of array?

### ISSUE THREAD

**Issue by luwes** [developit/htm#89]
Was wondering if it makes more sense that fragments return one `h` call of the produced array.

Similar to `h([h('div', 'First'), insertCat, h('div', 'Last')])`.

I'm asking since I ran into this issue myself using this lib without a VDOM library but with something like the original hyperscript. 

https://github.com/hyperhype/hyperscript/blob/master/index.js#L51

A plain array can't be appended as DOM nodes is the minor issue I guess.
It would be easy to transform the resulting array into a document fragment and append it but it would be nice the result of <code>html&#x60;&#x3C;div/&#x3E;&#x3C;div/&#x3E;&#x60;</code> could be appended as is.

Is there a way to do this? 
Or does it make more sense to have a plain array for most use cases?

Thanks

**Comment by developit** [comment]
This would be incompatible with current VDOM implementations, which use the form:

```js
const Fragment = props => props.children;

h(Fragment, null,
  h('a'),
  h('b')
)
```

The Array approach is preferable, since it avoids relying on these implementation details or adding new call signatures to h().

For Hyperscript, that call signature doesn't actually trigger the code on line 51, since the first argument is missing. Without modifying hyperscript's implementation to support Document Fragments, I don't think there's really a way to make this work within Hyperscript. It seems like the best approach here would be to patch htm's generated method to support fragments:

const h = require('hyperscript');
const htm = require('htm').bind(h);
function html() {
  const dom = htm.apply(this, arguments);
  if (Array.isArray(dom)) {
    const frag = document.createDocumentFragment();
    for (let i=0; i<dom.length; i++) frag.appendChild(dom[i]);
    return frag;
  }
  return dom;
}

**Comment by luwes** [comment]
Thanks @developit, makes sense. I was thinking it already supported arrays but it wouldn't have anything to put it on then.

A little torn on it though but I understand breaking existing VDOM implementations is not an option. 

Thanks for the snippet, I'll do some experimenting.

**Comment by luwes** [comment]
I think I'll have to make a fork unfortunately because it will get complicated with the precompile babel-plugin-htm. It's default is to use the `html` tag which most syntax highlighters also use.

Also Sinuous which I would like this functionality for does support fragments in the `h` tag. https://github.com/luwes/sinuous/blob/master/packages/sinuous/src/h.js#L50

Any chance you would accept an optional solution to wrap the array with an `h` tag?

I saw there is a `mini` version, maybe a `wrap` version or so?
Would need to be added to the babel plugin too then as an option.

**Comment by developit** [comment]
Hmm - why do you need the functionality in htm core though? The proxy function I wrote up in my previous comment should work, and `babel-plugin-htm` requires specifying a target module. You can point that to your proxied version:

```js
// babel.config.js
module.exports = {
	plugins: [
		['babel-plugin-transform-jsx-to-htm', {
			tag: '$$html',
			import: {
				module: require.resolve('./html.js'), // path to your function
				export: 'html'
			}
		}]
	]
}
```

```js
// file: html.js
import htm from 'htm';
import h from 'hyperscript';

const htmlMain = htm.bind(h);

// this is your html`` function:
export function html() {
  const dom = htm.apply(this, arguments);
  if (Array.isArray(dom)) {
    const frag = document.createDocumentFragment();
    for (let i=0; i<dom.length; i++) frag.appendChild(dom[i]);
    return frag;
  }
  return dom;
}
```

**Comment by luwes** [comment]
Sorry for the slow response @developit. 

Yea for myself it would totally do it but I hoped others that choose to use the library have as less friction as possible in setting the library up.

It definitely works like you explained, thanks for the useful info and code snippets!

Actually I might do some testing, this is not the worst config:

```js
// babel.config.js
module.exports = {
	plugins: [
		['htm', {
			tag: '$$html',
			import: {
				module: require.resolve('sinuous/html'), // for example
				export: 'html'
			}
		}]
	]
}
```
