### ISSUE TITLE
Cache is never used

### ISSUE THREAD

**Issue by dy** [developit/htm#95]
https://github.com/developit/htm/blob/c5764b5ce755cef1b54c85ee91b767bb8fdda422/src/index.mjs#L193-L199

Here map stores compiled result by statics array as a key. But - each time we call `` htm`statics` `` the statics array is always new one, therefore cache just gets bloated and never fetches existing result. That can be checked.

So since Map requires joining statics, same way as `getCacheKeyed`, there's no much sense to keep `getCacheMap`.

**Comment by developit** [comment]
The key is not recreated on each invocation, since Tagged Templates consistently reference the strings Array on subsequent calls, based on callsite.

```
const htm = strings => strings;

function test() {
  // on every call, the first argument to `htm` is the same reference:
  return htm`statics`;
}

test() === test()  // true
```

**Comment by jviide** [comment]
This can be demonstrated by instrumenting `getCacheMap` in the following way:

```js
const getCacheMap = statics => {
  let tpl = CACHE.get(statics);
  console.log("cache hit:", Boolean(tpl));
  if (!tpl) {
    CACHE.set(statics, (tpl = build(statics)));
  }
  return tpl;
};
```

Building the modified `htm` and using it the following way:

```js
const htm = require("./dist/htm");

const html = htm.bind((type, props, ...children) => ({
  type,
  props,
  children
}));

for (let i = 0; i < 5; i++) {
  html`
    statics
  `;
}
```

prints to the console:

```
cache hit: false
cache hit: true
cache hit: true
cache hit: true
cache hit: true
```

**Comment by dy** [comment]
If cache depends on callsite that’s still a bit of redundancy, not critical though I guess.

Thanks for the explanation, I have to check what I did wrong why I couldn’t reproduce that.

**Comment by jviide** [comment]
Yup, there'll be some redundancy. We figured that the performance win would be worth it in the long run, as the Map-based cache is quite a bit faster.

While the callsite-based behavior is in the specification (IIRC), there _are_ some platforms that diverge from the spec. For example some older TypeScript 2.x versions. Maybe you bumped into one of those cases?

**Comment by dy** [comment]
@jviide I thin I've tested that from "0 callsite" from the console, in which case it didn't work:
```js
let prev 
function x (s) {
console.log(s === prev)
prev = s
}
x`statics` // false
x`statics` // false
x`statics` // false
```

**Comment by dy** [comment]
Also - just out of curiosity - why there's `length` used?
https://github.com/developit/htm/blob/c5764b5ce755cef1b54c85ee91b767bb8fdda422/src/index.mjs#L204
instead of simple join `key = statics.join('-')`

**Comment by jviide** [comment]
That's because the cache key would then be non-unique. As an example, consider the cases when `statics` is `["a", "b-c"]` and when `statics` is `["a-b", "c"]`. In both of these cases the cache key would be `"a-b-c"`, and if both of those cases appeared in the same program there would be incorrect results. More thorough examples available in e.g. https://github.com/developit/htm/pull/22.
