### ISSUE TITLE
Escaping quotes inside of quotes

### ISSUE THREAD

**Issue by dy** [developit/htm#96]
There seem to be problems with escaping quotes as

```
h`<a x="ab\"c\"def" />`
```

The result is not what expected.

**Comment by jviide** [comment]
This behavior is intentional and acts similarly to JSX. If you want to have double quotes in a value you can use single quotes (e.g. `<a x='ab"c"def' />), and vice versa. If you want to have _both_ single and double quotes in a value, you can use a dynamic value (e.g. `<a x=${"ab\"c'def"} />`).

**Comment by timonson** [comment]
Hi @jviide , I would like to make sure that I understand the issue of *escaping* with regards to `htm` correctly and didn't want to open a new issue for that. I would appreciate it if you could give a quick reply to my question: We never need to escape the content of expressions inside the tagged templates, even if it is user input, right? Thank you very much!
